name: Helm Cloud Run

on:
  push:
    branches: [ develop, main ]
    tags: ['v*.*.*']

env:
  CHART_NAME: helm-cloud-run
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  GITHUB_TOKEN: ${{ secrets.EVER_PAT_GITHUB_TOKEN }}

jobs:
  build:    
    runs-on: ubuntu-latest
    container:
      image: gcr.io/its-artifact-commons/github-runner:develop-595f057    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build Helm
      id: build-helm-chart
      run: |
        run-prepare.bash
        ./run-helm-build.bash $(pwd) ${CHART_NAME}
